export const DECISIONS = {
    DECISION_UNKNOWN: 'DECISION_UNKNOWN',
    APPROVED: 'APPROVED',
    DENIED: 'DENIED',
    DECLINED:"DECLINED",
    UNRECOGNIZED: 'UNRECOGNIZED',
};

export const DECISIONS_TRANSLATE = {
    DECISION_UNKNOWN: 'לא הוחלטה',
    APPROVED: 'אושרה',
    DENIED: 'נדחתה',
    UNRECOGNIZED: 'לא ידועה',
};