name: "supernovaui"
# If you want to overide the full name you can include the 'fullnameOverride' value
#fullname:
replicaCount: 1

server:
  shouldPreconfigure: true
  preconfigureCommand:
    - "/bin/bash"
    - "/usr/share/preconfigure_server.sh"
images:
  PullSecrets:
    name: momentumacr
  repository: momentumacr.azurecr.io/supernovaui
  tag: "latest"

service:
  ports:
  - name: http
    port: "80"

config:
  configmaps:
      name: momentum-configmap

ingress:
  enabled: true
  hosts:
  - host: momentum.branch-yesodot.org
    paths:
      - path: /
        service: supernovaui
        port: 80